name: env_pdf
dependencies:
  - python=3.8
  - pip
  # - xlrd
  # - openpyxl
  - gensim
  #- jupyter    # for use in Jupyter notebook
  - ipykernel   # for recognition of conda env in Jupyter notebook
  # - pyg
  - pip:
    - pdfplumber==0.7.6
  #   - bertopic==0.12.0
    - spacy
    - nltk
    - scikit-learn
    - fasttext
  #  # - pyLDAvis    # for topic visual.
  #  # - matplotlib==3.6.2
  #  # - importlib
  #   - annoy
  #  # - sentence_transformers
  #   - networkx
