name: env_pdf
dependencies:
  - python=3.8
  - pip
  - pandas 
  # - xlrd
  # - openpyxl
  # - gensim
  #- jupyter    # for use in Jupyter notebook
  - ipykernel   # for recognition of conda env in Jupyter notebook
  # - pyg
  - pip:
    - pdfplumber==0.7.6
  #   - bertopic==0.12.0
  #   - spacy==3.4.3
  #   - nltk==3.7
  #   - fasttext==0.9.2
  #  # - pyLDAvis    # for topic visual.
  #  # - matplotlib==3.6.2
  #  # - importlib
  #   - annoy
  #  # - sentence_transformers
  #   - networkx
