[server]
port=5001  

[browser]
serverAddress="127.0.0.1"

[theme]
base="light"
primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#b3cbdd"
textColor="#262730"
font="serif"

#primaryColor="#6eb52f"
#backgroundColor="#f0f0f5"
#secondaryBackgroundColor="#e0e0ef"
#textColor="#262730"
#font="sans serif"